# Full reference https://github.com/foundry-rs/foundry/tree/master/crates/config

[profile.default]
  auto_detect_solc = false
  block_timestamp = 1_680_220_800 # March 31, 2023 at 00:00 GMT
  bytecode_hash = "none"
  evm_version = "shanghai"
  fuzz = { runs = 1_000 }
  gas_reports = ["*"]
  optimizer = true
  optimizer_runs = 10_000
  out = "out"
  script = "script"
  solc = "0.8.25"
  src = "src"
  test = "test"

[profile.ci]
  fuzz = { runs = 10_000 }
  verbosity = 4

[etherscan]
  arbitrum = { key = "${API_KEY_ARBISCAN}" }
  avalanche = { key = "${API_KEY_SNOWTRACE}" }
  base = { key = "${API_KEY_BASESCAN}" }
  bnb_smart_chain = { key = "${API_KEY_BSCSCAN}" }
  gnosis_chain = { key = "${API_KEY_GNOSISSCAN}" }
  goerli = { key = "${API_KEY_ETHERSCAN}" }
  mainnet = { key = "${API_KEY_ETHERSCAN}" }
  optimism = { key = "${API_KEY_OPTIMISTIC_ETHERSCAN}" }
  polygon = { key = "${API_KEY_POLYGONSCAN}" }
  sepolia = { key = "${API_KEY_ETHERSCAN}" }

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true

[rpc_endpoints]
  arbitrum = "https://rpc.ankr.com/arbitrum"
  avalanche = "https://rpc.ankr.com/avalanche"
  base = "https://mainnet.base.org"
  bnb_smart_chain = "https://bsc-dataseed.binance.org"
  gnosis_chain = "https://rpc.gnosischain.com"
  localhost = "http://localhost:8545"
  mainnet = "https://rpc.ankr.com/eth"
  optimism = "https://optimism.llamarpc.com"
  polygon = "https://rpc.ankr.com/polygon"
  sepolia = "https://rpc.ankr.com/eth_sepolia"
  fantom = "https://rpc.ankr.com/fantom"
  bsc = "https://binance.llamarpc.com"
  blast = "https://rpc.ankr.com/blast"
  moonriver = "https://moonriver.public.blastapi.io"
  gnosis = "https://rpc.ankr.com/gnosis"
  celo = "https://rpc.ankr.com/celo"